name: 'Gradle build Task'
description: 'Github Actions for Gradle build.'
author: 'Linjith'
inputs: 
  mode:
    description: 'Build mode'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mode }}
